export const CONVERSATION_HOME_COMPOSER_LAYOUT = {
  contentMaxWidthClassName: 'max-w-3xl',
  opticalBottomPaddingClassName: 'pb-[clamp(4rem,8vh,5rem)]',
  textareaMinHeightClassName: 'min-h-14',
  textareaMaxHeightPx: 320,
  containerClassName: '@container/conversation-composer flex flex-col gap-4',
  toolbarClassName: 'mt-3 grid grid-cols-1 gap-2 border-t border-border/40 pt-3 @2xl/conversation-composer:grid-cols-[minmax(12rem,0.75fr)_minmax(28rem,1.25fr)] @2xl/conversation-composer:items-center @2xl/conversation-composer:gap-3',
  leadingActionsClassName: 'flex min-w-0 items-center gap-2',
  workspaceControlClassName: 'min-w-0 max-w-none flex-1',
  trailingActionsClassName: 'grid min-w-0 grid-cols-1 gap-2 @sm/conversation-composer:grid-cols-2 @lg/conversation-composer:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_auto] @2xl/conversation-composer:flex @2xl/conversation-composer:items-center @2xl/conversation-composer:justify-end',
  configTriggerClassName: 'w-full max-w-none',
  sendButtonClassName: 'h-9 w-full gap-1.5 rounded-full px-4 @sm/conversation-composer:col-span-2 @lg/conversation-composer:col-span-1 @lg/conversation-composer:w-auto @2xl/conversation-composer:h-8 @2xl/conversation-composer:shrink-0 @2xl/conversation-composer:px-3',
  optionSectionClassName: 'flex flex-col items-stretch gap-2 rounded-xl border border-border/50 bg-card/40 px-4 py-3 @sm/conversation-composer:flex-row @sm/conversation-composer:items-center @sm/conversation-composer:gap-3',
  optionTabsListClassName: 'h-8 w-full @sm/conversation-composer:w-fit',
  agentSectionClassName: 'flex min-h-14 flex-col items-stretch gap-2 rounded-xl border border-border/50 bg-card/40 px-4 py-1 @sm/conversation-composer:flex-row @sm/conversation-composer:items-center',
  agentTabsClassName: 'gold-scrollbar-hidden w-full min-w-0 overflow-x-auto overflow-y-hidden py-1 @sm/conversation-composer:w-auto @sm/conversation-composer:flex-1',
  agentTabsListClassName: 'h-10 w-max max-w-none',
} as const;
