import { describe, expect, it } from 'vitest';
import { createDemoApi } from '../../marketing/demo/api';
import { demoPageFromHash } from '../../marketing/demo/routes';

const locator = ['default', 'demo-review', 'run-051', 'round-001', 'dev-test', 'attempt-001'] as const;
describe('demo historical read contracts', () => {
  it('preserves explicit unknown identities instead of substituting a sample', () => {
    expect(demoPageFromHash('#missing?project=another&run=run-999')).toMatchObject({ projectId: 'another', taskId: 'missing', runId: 'run-999' });
  });
  it('rejects outer and branch mismatches', async () => {
    const api = createDemoApi();
    await expect(api.getAcpSession(...locator, undefined, undefined, 'other', 'attempt-001')).rejects.toMatchObject({ code: 'demo.resource-not-found' });
    await expect(api.getAcpSession(...locator, { branchId: 'other' })).rejects.toMatchObject({ code: 'demo.resource-not-found' });
  });
  it('paginates without duplication or omissions', async () => {
    const api = createDemoApi();
    const full = await api.getAcpSession(...locator);
    const last = await api.getAcpSession(...locator, { pageSize: 2 });
    expect(last!.events).toHaveLength(2);
    expect(last!.eventPage.hasOlder).toBe(true);
    const earlier = await api.getAcpSession(...locator, { beforeCursor: last!.eventPage.oldestCursor!, pageSize: 100 });
    expect([...earlier!.events, ...last!.events]).toEqual(full!.events);
  });
  it('accepts the rev cursor generated by the shared chat window', async () => {
    const api = createDemoApi();
    const page = await api.getAcpSession(...locator, { beforeCursor: 'rev:4', beforeSeq: 4, pageSize: 2 });
    expect(page!.events.map((event) => event.seq)).toEqual([2, 3]);
    expect(page!.eventPage.oldestCursor).toBe('rev:2');
  });
  it('selects tool by complete identity and rejects unknown event', async () => {
    const api = createDemoApi();
    const session = (await api.getAcpSession(...locator))!;
    await expect(api.getAcpToolDetail(...locator, { branchId: session.branchId, sessionId: session.sessionId!, eventId: 'missing' })).rejects.toMatchObject({ code: 'demo.resource-not-found' });
  });
  it('honors activity range', async () => {
    const api = createDemoApi();
    const session = (await api.getAcpSession(...locator))!;
    expect(await api.getAcpActivityDetail(...locator, { branchId: session.branchId, sessionId: session.sessionId!, activityStartSeq: 1000, activityEndSeq: 2000 })).toMatchObject({ items: [] });
  });
});
