use anyhow::{Result, bail};
use std::ffi::OsStr;
use std::path::{Path, PathBuf};
use std::process::{Command as ProcessCommand, Stdio};

#[cfg(windows)]
use std::os::windows::process::CommandExt;

#[cfg(windows)]
const CREATE_NO_WINDOW: u32 = 0x08000000;

pub fn find_executable_in_path(name: &str) -> Option<PathBuf> {
    let path_var = std::env::var("PATH").ok()?;
    for dir in std::env::split_paths(&path_var) {
        #[cfg(windows)]
        {
            // On Windows, npm global installs create a shell-script shim with no
            // extension (e.g. `%APPDATA%/npm/claude`), a `.cmd` wrapper, and a
            // `.ps1` wrapper — all in the same directory.  The extensionless file
            // is a POSIX shell script that cannot be spawned by Windows or by
            // Node.js child_process.  Prefer `.exe`, then resolve `.cmd` → the
            // real `.exe`, and only fall back to the bare name as a last resort.
            let candidate_exe = dir.join(format!("{name}.exe"));
            if candidate_exe.is_file() {
                return Some(candidate_exe);
            }
            let candidate_cmd = dir.join(format!("{name}.cmd"));
            if candidate_cmd.is_file() {
                if let Some(resolved) = resolve_cmd_to_exe(&candidate_cmd) {
                    return Some(resolved);
                }
                return Some(candidate_cmd);
            }
        }
        let candidate = dir.join(name);
        if candidate.is_file() {
            return Some(candidate);
        }
    }
    None
}

/// Resolves a Windows `.cmd` wrapper script (typically generated by npm)
/// to the actual `.exe` binary it invokes.
///
/// npm-generated .cmd files follow the pattern:
/// ```cmd
/// "%dp0%\node_modules\@scope\package\bin\tool.exe" %*
/// ```
/// where `%dp0%` expands to the directory containing the .cmd file.
#[cfg(windows)]
pub fn resolve_cmd_to_exe(cmd_path: &Path) -> Option<PathBuf> {
    let ext = cmd_path.extension().and_then(|e| e.to_str())?;
    if !ext.eq_ignore_ascii_case("cmd") {
        return None;
    }
    let contents = std::fs::read_to_string(cmd_path).ok()?;
    let cmd_dir = cmd_path.parent()?;

    // Look for the last line that references an .exe with %dp0%
    for line in contents.lines().rev() {
        let trimmed = line.trim();
        if !trimmed.contains("%dp0%") {
            continue;
        }
        if !trimmed.to_lowercase().contains(".exe") {
            continue;
        }
        // Extract the quoted path or unquoted path containing %dp0%
        let exe_ref = extract_dp0_exe_path(trimmed)?;
        let resolved = exe_ref.replace("%dp0%", &cmd_dir.to_string_lossy());
        // Remove surrounding quotes if present
        let resolved = resolved.trim_matches('"');
        let resolved_path = PathBuf::from(resolved);
        if resolved_path.is_file() {
            return Some(resolved_path);
        }
    }
    None
}

/// Extracts the .exe path component from a .cmd line that contains %dp0%.
/// Handles patterns like:
/// - `"%dp0%\node_modules\...\tool.exe" %*`
/// - `%dp0%\node_modules\...\tool.exe %*`
#[cfg(windows)]
fn extract_dp0_exe_path(line: &str) -> Option<String> {
    let start = line.find("%dp0%")?;
    // Walk backward from the .exe reference to find the beginning
    let exe_end = line[start..].find(".exe")? + 4;
    let exe_in_line = &line[start..start + exe_end];

    // If there's a quote before %dp0%, use quoted boundaries
    if let Some(quote_pos) = line[..start].rfind('"') {
        if let Some(end_quote) = line[start + exe_end..].find('"') {
            let end = start + exe_end + end_quote + 1;
            return Some(line[quote_pos..end].to_string());
        }
    }

    // Unquoted: take %dp0%...exe path (may contain spaces, but we try our best)
    Some(exe_in_line.to_string())
}

#[cfg(not(windows))]
pub fn resolve_cmd_to_exe(_cmd_path: &Path) -> Option<PathBuf> {
    None
}

pub fn background_command(program: impl AsRef<OsStr>) -> ProcessCommand {
    let mut command = ProcessCommand::new(program);
    apply_background_process_flags(&mut command);
    command
}

pub fn apply_background_process_flags(command: &mut ProcessCommand) {
    #[cfg(windows)]
    command.creation_flags(CREATE_NO_WINDOW);
}

pub fn kill_process_tree(pid: u32) -> Result<()> {
    #[cfg(windows)]
    {
        let status = background_command("taskkill")
            .args(["/PID", &pid.to_string(), "/T", "/F"])
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status()?;
        if !status.success() {
            bail!("failed to kill provider process tree for pid {pid}");
        }
    }
    #[cfg(not(windows))]
    {
        let status = background_command("kill")
            .args(["-TERM", &pid.to_string()])
            .status()?;
        if !status.success() {
            bail!("failed to kill provider process for pid {pid}");
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[cfg(windows)]
    #[test]
    fn resolve_npm_cmd_to_exe_from_disk() {
        // Verify real system claude.cmd → claude.exe resolution
        let claude_cmd = PathBuf::from(
            r"C:\Users\91964\AppData\Roaming\npm\claude.cmd",
        );
        if claude_cmd.is_file() {
            let resolved = resolve_cmd_to_exe(&claude_cmd);
            assert!(resolved.is_some(), "should resolve claude.cmd to exe");
            let exe_path = resolved.unwrap();
            assert!(exe_path.is_file(), "resolved exe should exist: {exe_path:?}");
            assert!(exe_path.to_string_lossy().ends_with(".exe"));
        }
    }

    #[cfg(windows)]
    #[test]
    fn resolve_npm_cmd_pattern_quoted() {
        let dir = std::env::temp_dir().join("gold-band-test-resolve");
        std::fs::create_dir_all(&dir).unwrap();
        let cmd_path = dir.join("tool.cmd");
        let exe_path = dir.join("node_modules").join("@scope").join("pkg").join("bin").join("tool.exe");
        std::fs::create_dir_all(exe_path.parent().unwrap()).unwrap();
        std::fs::write(&exe_path, b"fake-exe").unwrap();

        let cmd_content = format!(
            "@ECHO off\r\nGOTO start\r\n:find_dp0\r\nSET dp0=%~dp0\r\nEXIT /b\r\n:start\r\nSETLOCAL\r\nCALL :find_dp0\r\n\"%dp0%\\node_modules\\@scope\\pkg\\bin\\tool.exe\"   %*\r\n"
        );
        std::fs::write(&cmd_path, cmd_content).unwrap();

        let resolved = resolve_cmd_to_exe(&cmd_path);
        assert!(resolved.is_some(), "should resolve tool.cmd to tool.exe");
        assert_eq!(resolved.unwrap(), exe_path);

        std::fs::remove_dir_all(&dir).unwrap();
    }

    #[cfg(windows)]
    #[test]
    fn resolve_cmd_returns_none_for_non_cmd() {
        let result = resolve_cmd_to_exe(Path::new("C:\\Windows\\System32\\cmd.exe"));
        assert!(result.is_none());
    }

    #[cfg(not(windows))]
    #[test]
    fn resolve_cmd_returns_none_on_unix() {
        let result = resolve_cmd_to_exe(Path::new("/usr/bin/some.cmd"));
        assert!(result.is_none());
    }
}
